# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-11 17:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pokebase', '0004_remove_trainer_trainer_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Pokedex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('type1', models.CharField(max_length=10)),
                ('type2', models.CharField(max_length=10)),
                ('base_power', models.PositiveIntegerField(default=1)),
                ('location', models.ManyToManyField(to='Pokebase.Location')),
            ],
        ),
        migrations.RenameField(
            model_name='pokemon',
            old_name='pokemon_name',
            new_name='nickname',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='pokemon_level',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='trainer_money',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='exp',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='gender',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='iv',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='level',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='power',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='trainer',
            name='money',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trainer',
            name='title',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pokemon',
            name='species',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='Pokebase.Pokedex'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainer',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='Pokebase.Location'),
            preserve_default=False,
        ),
    ]
