# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-11 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pokebase', '0005_auto_20160912_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokedex',
            name='picture',
            field=models.ImageField(null=True, upload_to='D:\\Data\\Project\\Python\\VCreate\\Pokehunt\\static\\img'),
        ),
    ]
